apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  labels:
    app: wikijs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
        - name: wikijs
          image: "requarks/wiki:2"
          ports:
            - name: http           # Das ist der Name, den deine Probes suchen
              containerPort: 3000  # Wiki.js lauscht intern immer auf 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: http           # Nutzt den oben definierten Namen
          readinessProbe:
            httpGet:
              path: /healthz
              port: http           # Nutzt den oben definierten Namen
          env:
            - name: DB_TYPE
              value: "sqlite"
            - name: DB_FILEPATH
              value: "/wiki/database.sqlite"
          volumeMounts:
            - name: wiki-data
              mountPath: /wiki
      volumes:
        - name: wiki-data
          emptyDir: {}
