{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: wikijs-postgresql-secret
  labels:
    app: wikijs-postgresql
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
{{- end }}
