{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs-postgresql
  labels:
    app: wikijs-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikijs-postgresql
  template:
    metadata:
      labels:
        app: wikijs-postgresql
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ .Values.postgresql.postgresqlPort }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUser | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wikijs-postgresql-secret
                  key: postgresql-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgresql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: postgresql-data
          {{- if .Values.postgresql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: wikijs-postgresql-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
